# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.9.16 # https://pyreadiness.org/3.9
  - pip=22.1.2 # https://pip.pypa.io/en/stable/news
  - pip:
      - rpaframework==28.6.1 # https://rpaframework.org/releasenotes.html
      - robocorp-tasks==3.1.1 # https://pypi.org/project/robocorp-tasks/#history
      - robocorp-vault==1.3.6 # https://pypi.org/project/robocorp-vault/#history
      - robocorp-workitems==1.4.5 # https://pypi.org/project/robocorp-workitems/#history
      - openai==1.37.1 # https://pypi.org/project/openai/#history
      - sendgrid==6.11.0 # https://pypi.org/project/sendgrid/#history
      - pypdf2 # https://pypi.org/project/pypdf2/#history

